Repository bprof-spec-codes/oetube, pull requests merged in 2023-10, with the labels that each got.

#18 Entities
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/oetube/FileContentIndex/077fc953-63d3-46e2-827b-d4e0b964ee40.vsidx
  .vs/oetube/FileContentIndex/23bc4bfe-8e1e-4113-9e9e-f7a7400010f1.vsidx
  .vs/oetube/FileContentIndex/5d4a95f2-486b-4727-9551-7e2df8497792.vsidx
  .vs/oetube/FileContentIndex/b606446b-c265-4ea3-8ba7-0a4c1d263b23.vsidx
  .vs/oetube/FileContentIndex/f0d6feb5-d0dd-4801-a124-16d9e6700c98.vsidx
  .vs/oetube/v17/.wsuo
  .vs/slnx.sqlite
  oetube/aspnet-core/OeTube/Entities/AccessGroup.cs
  oetube/aspnet-core/OeTube/Entities/Group.cs
  oetube/aspnet-core/OeTube/Entities/Member.cs
  oetube/aspnet-core/OeTube/Entities/Playlist.cs
  oetube/aspnet-core/OeTube/Entities/User.cs
  oetube/aspnet-core/OeTube/Entities/Video.cs
  oetube/aspnet-core/OeTube/Entities/VideoItem.cs
Labels: backend

#16 Video player
  oetube/angular/package-lock.json
  oetube/angular/package.json
  oetube/angular/src/app/services/video/video-time.service.spec.ts
  oetube/angular/src/app/services/video/video-time.service.ts
  oetube/angular/src/app/services/video/video.service.spec.ts
  oetube/angular/src/app/services/video/video.service.ts
  oetube/angular/src/app/services/video/volume.service.spec.ts
  oetube/angular/src/app/services/video/volume.service.ts
  oetube/angular/src/app/video/video-player/control-bar/control-bar.component.html
  oetube/angular/src/app/video/video-player/control-bar/control-bar.component.scss
  oetube/angular/src/app/video/video-player/control-bar/control-bar.component.spec.ts
  oetube/angular/src/app/video/video-player/control-bar/control-bar.component.ts
  oetube/angular/src/app/video/video-player/play-control/play-control.component.html
  oetube/angular/src/app/video/video-player/play-control/play-control.component.scss
  oetube/angular/src/app/video/video-player/play-control/play-control.component.spec.ts
  oetube/angular/src/app/video/video-player/play-control/play-control.component.ts
  oetube/angular/src/app/video/video-player/time/time.component.html
  oetube/angular/src/app/video/video-player/time/time.component.scss
  oetube/angular/src/app/video/video-player/time/time.component.spec.ts
  oetube/angular/src/app/video/video-player/time/time.component.ts
  oetube/angular/src/app/video/video-player/video-player.component.html
  oetube/angular/src/app/video/video-player/video-player.component.scss
  oetube/angular/src/app/video/video-player/video-player.component.ts
  oetube/angular/src/app/video/video-player/video-seeker/video-seeker.component.html
  oetube/angular/src/app/video/video-player/video-seeker/video-seeker.component.scss
  oetube/angular/src/app/video/video-player/video-seeker/video-seeker.component.spec.ts
  oetube/angular/src/app/video/video-player/video-seeker/video-seeker.component.ts
  oetube/angular/src/app/video/video-player/video-wrapper/video-wrapper.component.html
  oetube/angular/src/app/video/video-player/video-wrapper/video-wrapper.component.scss
  oetube/angular/src/app/video/video-player/video-wrapper/video-wrapper.component.spec.ts
  oetube/angular/src/app/video/video-player/video-wrapper/video-wrapper.component.ts
  oetube/angular/src/app/video/video-player/volume-control/volume-control.component.html
  oetube/angular/src/app/video/video-player/volume-control/volume-control.component.scss
  oetube/angular/src/app/video/video-player/volume-control/volume-control.component.spec.ts
  oetube/angular/src/app/video/video-player/volume-control/volume-control.component.ts
  oetube/angular/src/app/video/video.module.ts
  oetube/angular/src/index.html
  oetube/angular/yarn.lock
Labels: frontend

#48 47-fix-login
  oetube/angular/src/environments/environment.prod.ts
  oetube/angular/src/environments/environment.ts
  oetube/aspnet-core/OeTube/OeTubeModule.cs
Labels: bug, frontend, backend

#50 Request size limit changed to 1 gb
  oetube/aspnet-core/OeTube/OeTubeModule.cs
  oetube/aspnet-core/OeTube/web.config
Labels: backend
