Repository bprof-spec-codes/oetube, pull requests merged in 2023-12, with the labels that each got.

#81 61-group-editor-page
  oetube/angular/angular.json
  oetube/angular/src/app/app.module.ts
  oetube/angular/src/app/group/group-create/group-create.component.ts
  oetube/angular/src/app/group/group-details/group-details.component.html
  oetube/angular/src/app/group/group-details/group-details.component.ts
  oetube/angular/src/app/group/group-editor/group-create.component.scss
  oetube/angular/src/app/group/group-editor/group-editor.component.html
  oetube/angular/src/app/group/group-editor/group-editor.component.scss
  oetube/angular/src/app/group/group-editor/group-editor.component.spec.ts
  oetube/angular/src/app/group/group-editor/group-editor.component.ts
  oetube/angular/src/app/group/group-explore/group-explore.component.html
  oetube/angular/src/app/group/group-explore/group-explore.component.ts
  oetube/angular/src/app/group/group-explore/group-list-item/group-list-item.component.html
  oetube/angular/src/app/group/group-explore/group-tile-item/group-tile-item.component.html
  oetube/angular/src/app/group/group-routing.module.ts
  oetube/angular/src/app/group/group.component.html
  oetube/angular/src/app/group/group.component.ts
  oetube/angular/src/app/group/group.module.ts
  oetube/angular/src/app/lazy-tab-panel/lazy-tab-panel.component.html
  oetube/angular/src/app/lazy-tab-panel/lazy-tab-panel.component.ts
  oetube/angular/src/app/pagination-grid/creator-pagination-grid.component.ts
  oetube/angular/src/app/scroll-view/scroll-view-selector-popup/scroll-view-selector-popup.component.html
  oetube/angular/src/app/scroll-view/scroll-view-selector-popup/scroll-view-selector-popup.component.ts
  oetube/angular/src/app/scroll-view/scroll-view-selector/scroll-view-selector.component.html
  oetube/angular/src/app/scroll-view/scroll-view-selector/scroll-view-selector.component.spec.ts
  oetube/angular/src/app/scroll-view/scroll-view-selector/scroll-view-selector.component.ts
  oetube/angular/src/app/scroll-view/scroll-view.component.ts
  oetube/angular/src/app/scroll-view/scroll-view.module.ts
  oetube/angular/src/app/services/auth-url-pipe/auth-url.pipe.ts
  oetube/angular/src/app/services/current-user/current-user.service.ts
  oetube/angular/src/app/upload/upload.component.html
  oetube/angular/src/app/user/user-explore/user-explore.component.html
  oetube/angular/src/app/user/user-explore/user-explore.component.ts
  oetube/angular/src/app/user/user.component.html
  oetube/angular/src/app/video/video-grid/video-grid/video-grid.component.html
  oetube/angular/src/app/video/video-player/video-wrapper/video-wrapper.component.ts
  oetube/angular/src/app/video/video.module.ts
  oetube/angular/src/main.ts
  oetube/aspnet-core/OeTube/Application/Caches/Access/AccessCacheService.cs
  oetube/aspnet-core/OeTube/Data/QueryExtensions/VideoQueryExtension.cs
Labels: frontend

#83 82-video-frame-selector
  oetube/angular/src/app/group/group-explore/group-list-item/group-list-item.component.html
  oetube/angular/src/app/group/group-explore/group-tile-item/group-tile-item.component.html
  oetube/angular/src/app/proxy/application/dtos/videos/models.ts
  oetube/angular/src/app/services/auth-url-pipe/auth-url.pipe.ts
  oetube/angular/src/app/services/current-user/current-user.service.ts
  oetube/angular/src/app/services/url-service/url.service.ts
  oetube/angular/src/app/upload/upload.component.html
  oetube/angular/src/app/upload/upload.module.ts
  oetube/angular/src/app/upload/video-frame-selector/video-frame-selector.component.html
  oetube/angular/src/app/upload/video-frame-selector/video-frame-selector.component.scss
  oetube/angular/src/app/upload/video-frame-selector/video-frame-selector.component.spec.ts
  oetube/angular/src/app/upload/video-frame-selector/video-frame-selector.component.ts
  oetube/angular/src/app/user/user-explore/user-tile-item/user-tile-item.component.html
  oetube/angular/src/app/video/video-player/video-wrapper/video-wrapper.component.ts
  oetube/aspnet-core/OeTube/Application/Dtos/Videos/VideoIndexImagesDto.cs
Labels: frontend

#92 63 playlist page
  oetube/angular/src/app/playlist/playlist-routing.module.ts
  oetube/angular/src/app/playlist/playlist-view/playlist-view.component.html
  oetube/angular/src/app/playlist/playlist-view/playlist-view.component.scss
  oetube/angular/src/app/playlist/playlist-view/playlist-view.component.spec.ts
  oetube/angular/src/app/playlist/playlist-view/playlist-view.component.ts
  oetube/angular/src/app/playlist/playlist.module.ts
  oetube/aspnet-core/OeTube/Data/Repositories/Playlists/PlaylistRepository.cs
Labels: frontend, priority

#100 Endpoint documentation
  oetube/aspnet-core/OeTube/Application/GroupAppService.cs
  oetube/aspnet-core/OeTube/Application/OeTubeUserAppService.cs
  oetube/aspnet-core/OeTube/Application/PlaylistAppService.cs
  oetube/aspnet-core/OeTube/Application/VideoAppService.cs
  oetube/aspnet-core/OeTube/OeTube.csproj
  oetube/aspnet-core/OeTube/OeTubeModule.cs
  oetube/aspnet-core/OeTube/Swagger/AppServiceUtility.cs
  oetube/aspnet-core/OeTube/Swagger/ControllerCustomOrderFilter.cs
  oetube/aspnet-core/OeTube/Swagger/EndpointDocumentationFilter.cs
  oetube/aspnet-core/OeTube/endpoint.md
Labels: documentation, backend

#102 Playlist editor page
  oetube/angular/src/app/app.component.ts
  oetube/angular/src/app/collector.module.ts
  oetube/angular/src/app/double-click.directive.ts
  oetube/angular/src/app/lazy-tab-panel/lazy-tab-panel.component.ts
  oetube/angular/src/app/playlist/playlist-create/playlist-create.component.html
  oetube/angular/src/app/playlist/playlist-create/playlist-create.component.spec.ts
  oetube/angular/src/app/playlist/playlist-create/playlist-create.component.ts
  oetube/angular/src/app/playlist/playlist-details/playlist-details.component.html
  oetube/angular/src/app/playlist/playlist-details/playlist-details.component.scss
  oetube/angular/src/app/playlist/playlist-details/playlist-details.component.spec.ts
  oetube/angular/src/app/playlist/playlist-details/playlist-details.component.ts
  oetube/angular/src/app/playlist/playlist-editor/playlist-editor.component.html
  oetube/angular/src/app/playlist/playlist-editor/playlist-editor.component.ts
  oetube/angular/src/app/playlist/playlist-routing.module.ts
  oetube/angular/src/app/playlist/playlist-view/playlist-view.component.html
  oetube/angular/src/app/playlist/playlist-view/playlist-view.component.ts
  oetube/angular/src/app/playlist/playlist.component.html
  oetube/angular/src/app/playlist/playlist.component.ts
  oetube/angular/src/app/playlist/playlist.module.ts
  oetube/angular/src/app/scroll-view/scroll-view.component.html
  oetube/angular/src/app/scroll-view/scroll-view.component.scss
  oetube/angular/src/app/scroll-view/scroll-view.component.ts
  oetube/angular/src/app/scroll-view/scroll-view.module.ts
  oetube/angular/src/app/user/user-details/user-details.component.html
  oetube/angular/src/app/user/user-details/user-details.component.ts
  oetube/angular/src/app/user/user-update/user-update.component.html
  oetube/angular/src/app/user/user-update/user-update.component.ts
  oetube/angular/src/app/video/video-explore/video-contents/video-contents.component.ts
  oetube/aspnet-core/OeTube/Application/Dtos/Playlists/CreateUpdatePlaylistDto.cs
  oetube/aspnet-core/OeTube/Data/QueryExtensions/PlaylistQueryExtension.cs
  oetube/aspnet-core/OeTube/Data/QueryExtensions/VideoQueryExtension.cs
Labels: frontend

#107 Redirect when error
  oetube/angular/src/app/group/group-details/group-details.component.ts
  oetube/angular/src/app/playlist/playlist-details/playlist-details.component.ts
  oetube/angular/src/app/user/user-details/user-details.component.ts
  oetube/angular/src/app/video/video-details/video-details.component.ts
  oetube/angular/src/app/video/video-grid/video-grid/video-grid.component.html
Labels: frontend

#108 Frontend Validation
  oetube/angular/src/app/app.component.ts
  oetube/angular/src/app/group/group-details/group-details.component.html
  oetube/angular/src/app/group/group-editor/group-editor.component.html
  oetube/angular/src/app/group/group-editor/group-editor.component.ts
  oetube/angular/src/app/group/group-explore/group-contents/group-tile-item/group-tile-item.component.html
  oetube/angular/src/app/lazy-tab-panel/lazy-tab-panel.component.html
  oetube/angular/src/app/playlist/playlist-editor/playlist-editor.component.html
  oetube/angular/src/app/playlist/playlist-editor/playlist-editor.component.ts
  oetube/angular/src/app/playlist/playlist-explore/playlist-contents/playlist-list-item/playlist-list-item.component.html
  oetube/angular/src/app/proxy/application/dtos/index.ts
  oetube/angular/src/app/proxy/application/dtos/validations/index.ts
  oetube/angular/src/app/proxy/application/dtos/validations/models.ts
  oetube/angular/src/app/proxy/application/index.ts
  oetube/angular/src/app/proxy/application/validation.service.ts
  oetube/angular/src/app/proxy/generate-proxy.json
  oetube/angular/src/app/services/validation-store.service.spec.ts
  oetube/angular/src/app/services/validation-store.service.ts
  oetube/angular/src/app/user/user-details/user-details.component.html
  oetube/angular/src/app/user/user-explore/user-contents/user-tile-item/user-tile-item.component.html
  oetube/angular/src/app/user/user-update/user-update.component.html
  oetube/angular/src/app/user/user-update/user-update.component.ts
  oetube/angular/src/app/video/video-details/video-details.component.html
  oetube/angular/src/app/video/video-explore/video-contents/video-tile-item/video-tile-item.component.html
  oetube/angular/src/app/video/video-explore/video-contents/video-tile-item/video-tile-item.component.scss
  oetube/angular/src/app/video/video-update/video-update.component.html
  oetube/angular/src/app/video/video-update/video-update.component.ts
  oetube/angular/src/app/video/video-upload/video-upload.component.html
  oetube/angular/src/app/video/video-upload/video-upload.component.ts
  oetube/aspnet-core/OeTube/Application/Dtos/Validations/GroupValidationDto.cs
  oetube/aspnet-core/OeTube/Application/Dtos/Validations/PlaylistValidationDto.cs
  oetube/aspnet-core/OeTube/Application/Dtos/Validations/UserValidationDto.cs
  oetube/aspnet-core/OeTube/Application/Dtos/Validations/ValidationsDto.cs
  oetube/aspnet-core/OeTube/Application/Dtos/Validations/VideoValidationDto.cs
  oetube/aspnet-core/OeTube/Application/ValidationAppService.cs
  oetube/aspnet-core/OeTube/Domain/Entities/Videos/Video.cs
  oetube/aspnet-core/OeTube/endpoint.md
Labels: frontend, backend
